In [25]:
import numpy as np
import sys
import pandas as pd

array = np.random.randint(0, 101, size=(10, 5))

means = np.mean(array, axis=1)
medians = np.median(array, axis=1)
std_devs = np.std(array,axis=1)
mins = np.min(array,axis=1)
maxs = np.max(array, axis=1)

stats_table = pd.DataFrame({
    'Mean': means,
    'Median': medians,
    'Standard Deviation': std_devs,
    'Minimum': mins,
    'Maximum': maxs
})

print(array)
print(stats_table)


print (np.__version__)
print (sys.version)



[[ 11  31  15  39  59]
 [ 91  31  88  68  28]
 [ 75  51  25  30 100]
 [ 30  94  18  20  55]
 [ 14  39  20  37  81]
 [ 50  15  66  95  75]
 [ 46  72  42  34  51]
 [ 77  45  92  74   3]
 [ 43   6  18  50  32]
 [ 57  54  76  68  36]]
   Mean  Median  Standard Deviation  Minimum  Maximum
0  31.0    31.0           17.343587       11       59
1  61.2    68.0           27.080620       28       91
2  56.2    51.0           28.138230       25      100
3  43.4    30.0           28.520870       18       94
4  38.2    37.0           23.455490       14       81
5  60.2    66.0           26.873035       15       95
6  49.0    46.0           12.774976       34       72
7  58.2    74.0           31.517614        3       92
8  29.8    32.0           16.079801        6       50
9  58.2    57.0           13.600000       36       76
1.26.4
3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]
