In [3]:
import numpy as np
import sys
import pandas as pd

array = np.random.randint(0, 101, size=(10, 5))

means = np.mean(array, axis=1)
medians = np.median(array, axis=1)
std_devs = np.std(array,axis=1)
mins = np.min(array,axis=1)
maxs = np.max(array, axis=1)

stats_table = pd.DataFrame({
    'Mean': means,
    'Median': medians,
    'Standard Deviation': std_devs,
    'Minimum': mins,
    'Maximum': maxs
})

print(array)
print(stats_table)


print (np.__version__)
print (sys.version)



[[72  6 49  0  2]
 [ 6 87 12 87 88]
 [38 50 16  4 28]
 [98  4 35 38 43]
 [33  6 82 88 56]
 [96 74 52 60 82]
 [95 52 18 45 21]
 [50 96 64 48 51]
 [51 39 82 32 23]
 [58 26 60 77 76]]
   Mean  Median  Standard Deviation  Minimum  Maximum
0  25.8     6.0           29.314843        0       72
1  56.0    87.0           38.423951        6       88
2  27.2    28.0           16.129476        4       50
3  43.6    38.0           30.440762        4       98
4  53.0    56.0           30.607189        6       88
5  72.8    74.0           15.625620       52       96
6  46.2    45.0           27.737339       18       95
7  61.8    51.0           18.004444       48       96
8  45.4    39.0           20.460694       23       82
9  59.4    60.0           18.456435       26       77
1.26.4
3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]
