In [5]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [7]:
a[0]

1

In [9]:
a[1]

2

In [11]:
a[-1]

3

In [ ]:
import time
import sys


In [20]:
import time
import sys
b = range(1000)
print(sys.getsizeof(5) * len(b))

28000


In [22]:
import time
import sys
c = np.arange(1000)
print (c.size*c.itemsize)

8000


In [30]:
list1 = [0, 1, 2, 3, 4]
arr = np.array(list1)

print(type(arr))
arr+2


<class 'numpy.ndarray'>


array([2, 3, 4, 5, 6])

In [38]:
list2=[[0, 1, 2], [3, 4, 5]]
arr1 = np.array(list2, dtype=float)
arr1

array([[0., 1., 2.],
       [3., 4., 5.]])

In [46]:
arr1.astype('bool').astype('str')

array([['False', 'True', 'True'],
       ['True', 'True', 'True']], dtype='<U5')

In [56]:
arr3 = np.array([1, 2, 0], dtype='bool')
arr3

array([ True,  True, False])

In [70]:
arr4 = np.array([1, 'a'], dtype = 'object')
arr5 = arr4.tolist()
arr4


array([1, 'a'], dtype=object)

In [72]:
list3 = [[0, 1, 2, 3], [4, 5, 6, 7], [5, 6, 7, 8]]
arr2 = np.array(list3, dtype = 'float')
arr2

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.],
       [5., 6., 7., 8.]])

In [76]:
print ("Shape: ", arr2.shape)
print ("Data type: ", arr2.dtype)
print ("Size: ", arr2.size)
print ("Num Dimensions: ", arr2.ndim)

Shape:  (3, 4)
Data type:  float64
Size:  12
Num Dimensions:  2


In [78]:
arr2 [:2, :2]

array([[0., 1.],
       [4., 5.]])

In [80]:
b = arr2 > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [82]:
arr2[b]

array([5., 6., 7., 5., 6., 7., 8.])

In [84]:
arr2[::-1, ]

array([[5., 6., 7., 8.],
       [4., 5., 6., 7.],
       [0., 1., 2., 3.]])

In [86]:
arr2[::-1, ::-1]

array([[8., 7., 6., 5.],
       [7., 6., 5., 4.],
       [3., 2., 1., 0.]])

In [88]:
arr2[1,1] = np.nan
arr2[1,2] = np.inf
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4., nan, inf,  7.],
       [ 5.,  6.,  7.,  8.]])

In [90]:
missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4., -1., -1.,  7.],
       [ 5.,  6.,  7.,  8.]])

In [92]:
print ("Mean Value: ", arr2.mean())
print ("Max Value: ", arr2.max())
print ("Min Value: ", arr2.min())

Mean Value:  3.4166666666666665
Max Value:  8.0
Min Value:  -1.0


In [96]:
print ("Column wise minimun: ", np.amin(arr2, axis = 0))
print ("Row wise minimum: ", np.amin(arr2, axis = 1))

Column wise minimun:  [ 0. -1. -1.  3.]
Row wise minimum:  [ 0. -1.  5.]


In [98]:
np.cumsum(arr2)

array([ 0.,  1.,  3.,  6., 10.,  9.,  8., 15., 20., 26., 33., 41.])

In [100]:
arr2a = arr2[:2, :2].copy()
arr2a[:1, :1] = 101
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4., -1., -1.,  7.],
       [ 5.,  6.,  7.,  8.]])

In [104]:
arr2a

array([[101.,   1.],
       [  4.,  -1.]])

In [106]:
arr2[:1, :1]

array([[0.]])

In [108]:
#Reshaping and Flattening Multidimensional arrays:
arr2.reshape(4, 3)

array([[ 0.,  1.,  2.],
       [ 3.,  4., -1.],
       [-1.,  7.,  5.],
       [ 6.,  7.,  8.]])

In [110]:
#Difference between flatten and ravel=>ravel refer parent array
arr2.flatten()

array([ 0.,  1.,  2.,  3.,  4., -1., -1.,  7.,  5.,  6.,  7.,  8.])

In [112]:
b1 = arr2.flatten()
b1[0] = 100
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4., -1., -1.,  7.],
       [ 5.,  6.,  7.,  8.]])

In [114]:
b1

array([100.,   1.,   2.,   3.,   4.,  -1.,  -1.,   7.,   5.,   6.,   7.,
         8.])

In [116]:
b2 = arr2.ravel()
b2[0] = 101
arr2

array([[101.,   1.,   2.,   3.],
       [  4.,  -1.,  -1.,   7.],
       [  5.,   6.,   7.,   8.]])

In [118]:
b2

array([101.,   1.,   2.,   3.,   4.,  -1.,  -1.,   7.,   5.,   6.,   7.,
         8.])

In [120]:
#Create sequences, repetitions and random numbers 
print (np.arange(5))

[0 1 2 3 4]


In [122]:
print (np.arange(0, 10))


[0 1 2 3 4 5 6 7 8 9]


In [126]:
print (np.arange(0, 10, 2))

[0 2 4 6 8]


In [128]:
print (np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


In [130]:
np.linspace (start = 1, stop = 50, num = 10, dtype = int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [132]:
np.set_printoptions(precision = 2)
np.logspace(start = 1, stop = 50, num = 10, base = 10)

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [134]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [136]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
#Create repeating sequences:
import numpy as np
a = [1, 2, 3, 4, 5]
print ('Tile: ', np.tile(a, 2))

Tile:  [1 2 3 4 5 1 2 3 4 5]


In [144]:
print ("Repeat: ", np.repeat(a, 2))

Repeat:  [1 1 2 2 3 3 4 4 5 5]


In [146]:
#Generate random numbers:
print (np.random.rand(2, 2))

[[0.5  0.4 ]
 [0.48 0.11]]


In [148]:
print (np.random.randn(2, 2))

[[ 2.08 -1.81]
 [-1.19  0.28]]


In [150]:
print (np.random.randint(0, 10, size = [2,2]))

[[3 3]
 [7 3]]


In [152]:
print (np.random.random())
print (np.random.random(size = [2, 2]))

0.03336921443362906
[[0.05 0.46]
 [0.91 0.12]]


In [156]:
print (np.random.choice(['a', 'u', 'o', 'e', 'i'], size = 10))
print (np.random.choice(['a', 'u', 'o', 'e', 'i'], size = 10, p = [0.3, .1, 0.1, 0.4, 0.1]))
       

['e' 'o' 'a' 'e' 'u' 'o' 'i' 'i' 'a' 'e']
['u' 'a' 'u' 'a' 'e' 'a' 'o' 'e' 'a' 'e']


In [158]:
rn = np.random.RandomState(100)
print (rn.rand(2, 2))

[[0.54 0.28]
 [0.42 0.84]]


In [162]:
np.random.seed(100)
print(np.random.rand(2, 2))

[[0.54 0.28]
 [0.42 0.84]]


In [164]:

#Get the unique items and the counts

#Create random integers of size 10 between [0, 10):
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size = 10)
print (arr_rand)


[8 8 3 7 7 0 4 2 5 2]


In [168]:
#Get the unique items and their counts:
uniqs, counts = np.unique(arr_rand, return_counts = True)
print("Unique items: ", uniqs)
print("Counts: ", counts)


Unique items:  [0 2 3 4 5 7 8]
Counts:  [1 2 1 1 1 2 2]
