In [1]:
import numpy as np
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print ("Array: ", arr_rand)

index_gt5 = np.where(arr_rand > 5)
print ("Positions where value > 5: ", index_gt5)

Array:  [8 8 3 7 7 0 4 2 5 2]
Positions where value > 5:  (array([0, 1, 3, 4]),)


In [3]:
arr_rand.take(index_gt5)

array([[8, 8, 7, 7]])

In [5]:
np.where(arr_rand > 5, 'gt5', 'le5')

array(['gt5', 'gt5', 'le5', 'gt5', 'gt5', 'le5', 'le5', 'le5', 'le5',
       'le5'], dtype='<U3')

In [7]:
print ("Position of max value: ", np.argmax(arr_rand))
print ("Position of min value: ", np.argmin(arr_rand))

Position of max value:  0
Position of min value:  5


In [9]:
#Turn off scientific notation:
np.set_printoptions(suppress = True)
#import data from csv file:
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(path, delimiter=',', skip_header=1, filling_values=-999, dtype='float')
data[:3]  # see first 3 rows

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
        -999. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
        -999. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
        -999. ]])

In [15]:
#Handle datasets that has both numbers and text columns:
data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)
data2[:3]

/var/folders/05/310yv1ls3hs58pczf9v97xvr0000gn/T/ipykernel_8288/3583732618.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', 'S38')])

In [19]:
np.savetxt("out.csv", data, delimiter = ',') #save the array as a csv file


In [37]:
#save and load numpy objects:
#save single numpy array object as .npy file:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d_f = np.arange(10)
arr2d_b = np.arange(10)
np.save('myarray.npy', arr2d)
#save multiple numpy arrays as .npz file:
np.savez('array.npz', arr2d_f, arr2d_b)


In [39]:
#load back the .npy file:
a = np.load('myarray.npy')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
#load back the .npz file:
b = np.load('array.npz')
print(b.files)
b['arr_0']

['arr_0', 'arr_1']


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#How to concatenate two numpy arrays columnwise and row wise:
#3 ways: np.concatenate, np.vstack and np.hstack, np.r_ and np.c_
#All three methods provide the same output. One key difference to notice is unlike the other 2 methods, both np.r_ and np.c_ use square brackets to stack arrays
a = np.zeros([4, 4])
b = np.ones([4, 4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [51]:
#Vertical stack equivalents: (row wise)
np.concatenate([a,b], axis = 0)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.vstack([a, b])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.r_[a, b]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
#column wise:
np.concatenate([a, b], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [59]:
np.hstack([a, b])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [61]:
np.c_[a, b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [63]:
print(np.c_[a,b])

[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


In [65]:
#can also use np.r_ to create more complex number sequences in 1d arrays:
np.r_[[1, 2, 3], 0, 0, [4, 5, 6]]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [76]:
arr3 = np.random.randint(1, 6, size = [8,4])
arr3

array([[4, 4, 1, 1],
       [2, 1, 1, 1],
       [4, 5, 3, 1],
       [2, 1, 1, 5],
       [3, 4, 2, 5],
       [4, 5, 3, 5],
       [5, 1, 2, 4],
       [5, 2, 3, 3]])

In [78]:
np.sort(arr3, axis = 0)

array([[2, 1, 1, 1],
       [2, 1, 1, 1],
       [3, 1, 1, 1],
       [4, 2, 2, 3],
       [4, 4, 2, 4],
       [4, 4, 3, 5],
       [5, 5, 3, 5],
       [5, 5, 3, 5]])

In [82]:
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x) #sort index
print (sort_index)

[0 3 2 4 5 1]


In [84]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

In [86]:
#Argsort the 1st column:
sorted_index_1stcol = arr3[:, 0].argsort()
#Sort array by 1st column without disturbing the integrity of row:
arr3[sorted_index_1stcol]

array([[2, 1, 1, 1],
       [2, 1, 1, 5],
       [3, 4, 2, 5],
       [4, 4, 1, 1],
       [4, 5, 3, 1],
       [4, 5, 3, 5],
       [5, 1, 2, 4],
       [5, 2, 3, 3]])

In [88]:
#Sort in decreasing order:
arr3[sorted_index_1stcol[::-1]]

array([[5, 2, 3, 3],
       [5, 1, 2, 4],
       [4, 5, 3, 5],
       [4, 5, 3, 1],
       [4, 4, 1, 1],
       [3, 4, 2, 5],
       [2, 1, 1, 5],
       [2, 1, 1, 1]])

In [90]:
#Sort a numpy based on 2 or more columns:
#sort by col 0, then by col 1:
lexsorted_index = np.lexsort((arr3[:, 1], arr3[:, 0]))
arr3[lexsorted_index]

array([[2, 1, 1, 1],
       [2, 1, 1, 5],
       [3, 4, 2, 5],
       [4, 4, 1, 1],
       [4, 5, 3, 1],
       [4, 5, 3, 5],
       [5, 1, 2, 4],
       [5, 2, 3, 3]])