In [1]:
import numpy as np
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print ("Array: ", arr_rand)

index_gt5 = np.where(arr_rand > 5)
print ("Positions where value > 5: ", index_gt5)

Array:  [8 8 3 7 7 0 4 2 5 2]
Positions where value > 5:  (array([0, 1, 3, 4]),)


In [3]:
arr_rand.take(index_gt5)

array([[8, 8, 7, 7]])

In [5]:
np.where(arr_rand > 5, 'gt5', 'le5')

array(['gt5', 'gt5', 'le5', 'gt5', 'gt5', 'le5', 'le5', 'le5', 'le5',
       'le5'], dtype='<U3')

In [7]:
print ("Position of max value: ", np.argmax(arr_rand))
print ("Position of min value: ", np.argmin(arr_rand))

Position of max value:  0
Position of min value:  5


In [9]:
#Turn off scientific notation:
np.set_printoptions(suppress = True)
#import data from csv file:
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(path, delimiter=',', skip_header=1, filling_values=-999, dtype='float')
data[:3]  # see first 3 rows

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
        -999. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
        -999. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
        -999. ]])

In [15]:
#Handle datasets that has both numbers and text columns:
data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)
data2[:3]

/var/folders/05/310yv1ls3hs58pczf9v97xvr0000gn/T/ipykernel_8288/3583732618.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', 'S38')])

In [19]:
np.savetxt("out.csv", data, delimiter = ',') #save the array as a csv file


In [37]:
#save and load numpy objects:
#save single numpy array object as .npy file:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d_f = np.arange(10)
arr2d_b = np.arange(10)
np.save('myarray.npy', arr2d)
#save multiple numpy arrays as .npz file:
np.savez('array.npz', arr2d_f, arr2d_b)


In [39]:
#load back the .npy file:
a = np.load('myarray.npy')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
#load back the .npz file:
b = np.load('array.npz')
print(b.files)
b['arr_0']

['arr_0', 'arr_1']


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#How to concatenate two numpy arrays columnwise and row wise:
#3 ways: np.concatenate, np.vstack and np.hstack, np.r_ and np.c_
#All three methods provide the same output. One key difference to notice is unlike the other 2 methods, both np.r_ and np.c_ use square brackets to stack arrays
a = np.zeros([4, 4])
b = np.ones([4, 4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [51]:
#Vertical stack equivalents: (row wise)
np.concatenate([a,b], axis = 0)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.vstack([a, b])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.r_[a, b]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
#column wise:
np.concatenate([a, b], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [59]:
np.hstack([a, b])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [61]:
np.c_[a, b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [63]:
print(np.c_[a,b])

[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


In [65]:
#can also use np.r_ to create more complex number sequences in 1d arrays:
np.r_[[1, 2, 3], 0, 0, [4, 5, 6]]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [76]:
arr3 = np.random.randint(1, 6, size = [8,4])
arr3

array([[4, 4, 1, 1],
       [2, 1, 1, 1],
       [4, 5, 3, 1],
       [2, 1, 1, 5],
       [3, 4, 2, 5],
       [4, 5, 3, 5],
       [5, 1, 2, 4],
       [5, 2, 3, 3]])

In [78]:
np.sort(arr3, axis = 0)

array([[2, 1, 1, 1],
       [2, 1, 1, 1],
       [3, 1, 1, 1],
       [4, 2, 2, 3],
       [4, 4, 2, 4],
       [4, 4, 3, 5],
       [5, 5, 3, 5],
       [5, 5, 3, 5]])

In [82]:
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x) #sort index
print (sort_index)

[0 3 2 4 5 1]


In [84]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

In [86]:
#Argsort the 1st column:
sorted_index_1stcol = arr3[:, 0].argsort()
#Sort array by 1st column without disturbing the integrity of row:
arr3[sorted_index_1stcol]

array([[2, 1, 1, 1],
       [2, 1, 1, 5],
       [3, 4, 2, 5],
       [4, 4, 1, 1],
       [4, 5, 3, 1],
       [4, 5, 3, 5],
       [5, 1, 2, 4],
       [5, 2, 3, 3]])

In [88]:
#Sort in decreasing order:
arr3[sorted_index_1stcol[::-1]]

array([[5, 2, 3, 3],
       [5, 1, 2, 4],
       [4, 5, 3, 5],
       [4, 5, 3, 1],
       [4, 4, 1, 1],
       [3, 4, 2, 5],
       [2, 1, 1, 5],
       [2, 1, 1, 1]])

In [90]:
#Sort a numpy based on 2 or more columns:
#sort by col 0, then by col 1:
lexsorted_index = np.lexsort((arr3[:, 1], arr3[:, 0]))
arr3[lexsorted_index]

array([[2, 1, 1, 1],
       [2, 1, 1, 5],
       [3, 4, 2, 5],
       [4, 4, 1, 1],
       [4, 5, 3, 1],
       [4, 5, 3, 5],
       [5, 1, 2, 4],
       [5, 2, 3, 3]])

In [92]:
#working with dates:
#Create a datetime64 object:
date64 = np.datetime64('2024-08-11T23:28:30')
date64

numpy.datetime64('2024-08-11T23:28:30')

In [96]:
dt64 = np.datetime64(date64, 'D')
dt64

numpy.datetime64('2024-08-11')

In [100]:
#Create the timedeltas(individual units of time):
ten_min = np.timedelta64(10, 'm') #10 min
ten_sec = np.timedelta64(10, 's')
tennanoseconds = np.timedelta64(10, 'ns')

print("Add 10 days: ", dt64+10)
print("Add 10 minutes: ", dt64+ten_min)
print("Add 10 seconds: ", dt64+ten_sec)
print("Add 10 nanoseconds: ", dt64+tennanoseconds)

Add 10 days:  2024-08-21
Add 10 minutes:  2024-08-11T00:10
Add 10 seconds:  2024-08-11T00:00:10
Add 10 nanoseconds:  2024-08-11T00:00:00.000000010


In [102]:
#Convert np.datetime64 back to a string:
np.datetime_as_string(dt64)

'2024-08-11'

In [104]:
print ("Date: ", dt64)
print ("Is it a business day? ", np.is_busday(dt64))
print ("Add 2 business days, rolling forward do nearest biz day: ", np.busday_offset(dt64, 2, roll = 'forward'))
print ("Add 2 business days, rolling backward to nearest biz day: ", np.busday_offset(dt64, 2, roll = 'backward'))
       

Date:  2024-08-11
Is it a business day?  False
Add 2 business days, rolling forward do nearest biz day:  2024-08-14
Add 2 business days, rolling backward to nearest biz day:  2024-08-13


In [106]:
#Create a date sequence:
dates = np.arange(np.datetime64('2024-08-01'), np.datetime64('2024-08-10'))
print(dates)

np.is_busday(dates)

['2024-08-01' '2024-08-02' '2024-08-03' '2024-08-04' '2024-08-05'
 '2024-08-06' '2024-08-07' '2024-08-08' '2024-08-09']


array([ True,  True, False, False,  True,  True,  True,  True,  True])

In [108]:
#Convert numpy.datetime64 to datetime.datetime object:
import datetime
dt = dt64.tolist()
dt

datetime.date(2024, 8, 11)

In [112]:
print ("Year: ", dt.year)
print ("Day of month: ", dt.day)
print ("Month of year: ", dt.month)
print ("Day of week: ", dt.weekday()) #Sunday

Year:  2024
Day of month:  11
Month of year:  8
Day of week:  6


In [114]:
#Advanced numpy functions:

#vectorize:
#Define a scalar function:
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2

#On a scalar:
print("x = 10 returns ", foo(10))
print("x = 11 returns ", foo(11))

x = 10 returns  5.0
x = 11 returns  121


In [116]:
#vectorize foo, make it work on vectors:
foo_v = np.vectorize(foo, otypes = [float])
print("x = [10, 11, 12] returns ", foo_v([10, 11, 12]))
print("x = [[10, 11, 12], [1, 2, 3]] returns ", foo_v([[10, 11, 12], [1, 2, 3]] ))

x = [10, 11, 12] returns  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] returns  [[  5. 121.   6.]
 [  1.   1.   9.]]


In [118]:
#Apply along axis - apply a function column wise or row wise:
#Create a 2D array:
np.random.seed(100)
arr_x = np.random.randint(1, 10, size = [4, 10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [122]:
#tim su khac nhau giua gia tri max va min trong 1 hang/cot
def max_minus_min(x):
    return np.max(x) - np.min(x)
#Apply along the rows:
print("Row wise: ", np.apply_along_axis(max_minus_min, 1, arr = arr_x))

#Apply along the columns:
print("Column wise: ", np.apply_along_axis(max_minus_min, 0, arr = arr_x))


Row wise:  [8 8 6 8]
Column wise:  [7 8 2 7 6 5 8 5 5 5]


In [124]:
#Searchsorted: find the location to insert so the array will remain sorted:
x = np.arange(10)
print ("Where should 5 be inserted?: ", np.searchsorted(x, 5))
print ("Where should 5 be inserted (right)?: ", np.searchsorted(x, 5, side = 'right'))

Where should 5 be inserted?:  5
Where should 5 be inserted (right)?:  6


In [126]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
lst = range(10000)
lst

range(0, 10000)

In [130]:
probs = np.random.random(10000); probs /= probs.sum()
%timeit lst[np.searchsorted(probs.cumsum(), np.random.random())]
%timeit np.random.choice(lst, p=probs)

37 μs ± 803 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
462 μs ± 13.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [132]:
#Add a new axis to a numpy array:
x = np.arange(5)
print ("Original array: ", x)

#Introduce a new column axis:
x_col = x[:, np.newaxis]
print("x_col's shape: ", x_col.shape)
print(x_col)


Original array:  [0 1 2 3 4]
x_col's shape:  (5, 1)
[[0]
 [1]
 [2]
 [3]
 [4]]


In [134]:
#Introduce a new row axis:
x_row = x[np.newaxis, :]
print("x_row's shape: ", x_row.shape)
print(x_row)

x_row's shape:  (1, 5)
[[0 1 2 3 4]]


In [142]:
#Digitize:
#Create the array and bins:
import numpy as np
x = np.arange(10)

bins = np.array([0, 3, 6, 9])

#Get bin allotments:
np.digitize(x, bins)


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
#Clip:
#Cap all elements of x to lie between 3 and 8:
np.clip(x, 3, 8)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 8])

In [148]:
np.clip(x, 5, 8)

array([5, 5, 5, 5, 5, 5, 6, 7, 8, 8])

In [152]:
#Histogram and bincount:

#Bincount example:
x = np.array([1, 2, 2, 2, 2, 4, 4, 5, 6, 6, 6]) #doesnt need to be sorted
np.bincount(x) #0 occurs 0 times, 1->1 times...


array([0, 1, 4, 0, 2, 1, 3])

In [158]:
#Histogram example:
counts, bins = np.histogram(x, [0, 2, 4, 6, 8])
print ("Counts: ", counts)
print ("Bins: ", bins)

Counts:  [1 4 3 3]
Bins:  [0 2 4 6 8]
