In [1]:
import numpy as np
print (np.__version__)

1.26.4


In [5]:
import sys
print (sys.version)

3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]


In [11]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.ones((3, 3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = (arr % 2 == 1)
arr[b]

array([1, 3, 5, 7, 9])

In [41]:
b = (arr % 2 == 1)
arr[b] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [47]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = arr.copy()
arr2[arr2 % 2 == 1]

array([1, 3, 5, 7, 9])

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr3 = np.arange(10)
print (arr3.reshape(2, 5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
b = np.repeat(1, 10).reshape(2, -1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])