# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()

a = np.array([1, 2, 3])
a
# Create a 2-dimensional NumPy array using np.array()
b = np.array([[1, 2], [3, 4]])
b

# Create a 3-dimensional Numpy array using np.array()
c = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [1, 2, 3]]
])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

(3,)
3
int64
1


In [11]:
# Attributes of 2-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b.size)
print(b.dtype)
print(b.ndim)

(2, 3)
6
int64
2


In [13]:
# Attributes of 3-dimensional array
c = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [1, 2, 3]],
    [[4, 5, 5], [1, 2, 5]]
])
print(c.shape)
print(c.size)
print(c.dtype)
print(c.ndim)

(3, 2, 3)
18
int64
3


In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd



In [15]:
# Create an array of shape (10, 2) with only ones
a = np.ones(shape=(10, 2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
# Create an array of shape (7, 2, 3) of only zeros
b = np.zeros(shape=(7, 2, 3))
print(b)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [17]:
# Create an array within a range of 0 and 100 with step 3
print(np.arange(0, 100, 3 ))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [19]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a = np.random.randint(0, 11, size = (7, 2))
a

array([[7, 7],
       [7, 4],
       [4, 5],
       [2, 8],
       [4, 5],
       [1, 2],
       [4, 3]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
b = np.random.rand(3, 5)
b

array([[0.79103292, 0.30558824, 0.77071606, 0.19094611, 0.19491611],
       [0.68414248, 0.00557588, 0.81694029, 0.73469009, 0.38498301],
       [0.75660503, 0.62753987, 0.44938347, 0.1791464 , 0.52958528]])

In [22]:
# Set the random seed to 42
import random
random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
c = np.random.randint(0, 10, size = (4, 6))
c

array([[9, 5, 8, 8, 6, 6],
       [6, 8, 8, 7, 7, 2],
       [6, 5, 4, 6, 3, 4],
       [2, 2, 3, 3, 0, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [25]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
d = np.random.randint(1, 10, size = (3, 7))
d
# Find the unique numbers in the array you just created
uniqs, counts = np.unique(d, return_counts = True)
uniqs

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Find the 0'th index of the latest array you created
d[0]

array([8, 4, 7, 1, 6, 2, 9])

In [27]:
# Get the first 2 rows of latest array you created
first2rows = d[:2]
print(first2rows)

[[8 4 7 1 6 2 9]
 [4 5 9 4 6 3 4]]


In [33]:
# Get the first 2 values of the first 2 rows of the latest array
f = d[:2, :1]
f


array([[8],
       [4]])

In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a = np.random.randint(0, 10, size = (3, 5))
b = np.ones(shape = (3, 5))


In [40]:
# Add the two arrays together
c = a + b
print(c)

[[ 7. 10.  4.  6.  9.]
 [ 4.  4.  1.  2.  3.]
 [ 8.  3.  8. 10.  3.]]


In [38]:
# Create another array of ones of shape (5, 3)
arr = np.ones(shape = (5, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
# Try add the array of ones and the other most recent array together
arr2 = arr.reshape(3, 5)
print(arr2 + c)


[[ 8. 11.  5.  7. 10.]
 [ 5.  5.  2.  3.  4.]
 [ 9.  4.  9. 11.  4.]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [45]:
# Create another array of ones of shape (3, 5)
arr3 = np.ones(shape = (3, 5))

In [48]:
# Subtract the new array of ones from the other most recent array
arr4 = c - arr3
print (arr4)

[[6. 9. 3. 5. 8.]
 [3. 3. 0. 1. 2.]
 [7. 2. 7. 9. 2.]]


In [49]:
# Multiply the ones array with the latest array
arr3 * arr4

array([[6., 9., 3., 5., 8.],
       [3., 3., 0., 1., 2.],
       [7., 2., 7., 9., 2.]])

In [50]:
# Take the latest array to the power of 2 using '**'
arr4**2

array([[36., 81.,  9., 25., 64.],
       [ 9.,  9.,  0.,  1.,  4.],
       [49.,  4., 49., 81.,  4.]])

In [51]:
# Do the same thing with np.square()
np.square(arr4)

array([[36., 81.,  9., 25., 64.],
       [ 9.,  9.,  0.,  1.,  4.],
       [49.,  4., 49., 81.,  4.]])

In [52]:
# Find the mean of the latest array using np.mean()
np.mean(arr4)

4.466666666666667

In [53]:
# Find the maximum of the latest array using np.max()
np.max(arr4)

9.0

In [54]:
# Find the minimum of the latest array using np.min()
np.min(arr4)

0.0

In [61]:
# Find the standard deviation of the latest array
import statistics
print(statistics.stdev([1, 2, 3, 4]))

1.2909944487358056


In [63]:
# Find the variance of the latest array
print(statistics.variance([1, 2, 3, 4]))

1.6666666666666667


In [58]:
# Reshape the latest array to (3, 5, 1)
arr.reshape(3, 5, 1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [65]:
# Transpose the latest array
a = np.array([[1, 2], [3, 4]])
np.transpose(a)

array([[1, 3],
       [2, 4]])

What does the transpose do?

In [68]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a = np.random.randint(0, 10, size = (3, 3))
b = np.random.randint(0, 10, size = (3, 2))
print(a)
print(b)
print(np.transpose(a))
print(np.transpose(b))

[[3 5 7]
 [8 0 7]
 [3 1 8]]
[[1 2]
 [0 4]
 [4 0]]
[[3 8 3]
 [5 0 1]
 [7 7 8]]
[[1 0 4]
 [2 4 0]]


In [ ]:
# Perform a dot product on the two newest arrays you created


In [69]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
c = np.random.randint(0, 10, size = (4, 3))
d = np.random.randint(0, 10, size = (4, 3))
print(c)
print(d)

[[8 5 8]
 [7 4 3]
 [8 0 9]
 [4 7 2]]
[[8 7 8]
 [6 9 7]
 [8 7 8]
 [6 3 8]]


In [102]:
# Perform a dot product on the two newest arrays you created
c = np.array([[8, 5, 8],
 [7, 4, 3],
 [8, 0, 9],
 [4, 7, 2]])
d = np.array([[8, 7, 8],
 [6, 9, 7],
 [8, 7, 8],
 [6, 3, 8]])
mul = np.dot(c, d.T)
print(mul)

[[163 149 163 127]
 [108  99 108  78]
 [136 111 136 120]
 [ 97 101  97  61]]


It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [72]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a = np.random.randint(0, 10, size = (1, 5))
b = np.random.randint(0, 10, size = (1, 5))
print(a)
print(b)


[[1 7 4 1 9]]
[[4 3 2 7 0]]
[[False  True  True False  True]]


In [73]:
# Compare the two arrays with '>'
print(a>b)

[[False  True  True False  True]]


What happens when you compare the arrays with `>`?

In [74]:
# Compare the two arrays with '>='
print(a>=b)

[[False  True  True False  True]]


In [75]:
# Find which elements of the first array are greater than 7
c = a>7
print(a[c])

[9]


In [ ]:
# Which parts of each array are equal? (try using '==')


In [84]:
# Sort one of the arrays you just created in ascending order
a = [3, 5, 4, 8, 2]
a.sort()
print(a)

[2, 3, 4, 5, 8]


In [87]:
# Sort the indexes of one of the arrays you just created


In [92]:
# Find the index with the maximum value in one of the arrays you've created
b = np.array([1, 3, 6, 5, 2])
print(np.argmax(b))

2


In [93]:
# Find the index with the minimum value in one of the arrays you've created
print(np.argmin(b))

0


In [95]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
arr = np.array([[1, 2], [5, 4]])
print(np.argmax(arr, axis = 1))

[1 0]


In [96]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print(np.argmin(arr, axis = 0))

[0 0]


In [97]:
# Create an array of normally distributed random numbers
mean = 0       # Mean of the distribution
std_dev = 1    # Standard deviation of the distribution
size = (3, 4)  # Shape of the array

# Create an array of normally distributed random numbers
normal_array = np.random.normal(loc=mean, scale=std_dev, size=size)

print(normal_array)

[[-3.77274465e-01  8.28599648e-01 -3.67649869e-01  8.84230126e-01]
 [ 1.43319379e-01 -1.88204336e+00  1.51262570e+00 -5.33905205e-04]
 [-1.76315129e+00  2.02186839e+00  1.32913787e+00  2.27702495e+00]]


In [98]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr = np.linspace(1, 100, 10)
print(arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.